### ISSUE TITLE
[Feature Request] Add support to mount existing EFI partition and copy machine information

### ISSUE THREAD

**Issue by chrismanivong** [lzhoang2801/OpCore-Simplify#12]
It would be great to have the ability to mount an existing EFI partition and look for the config.plist.
Users should be able to copy their machine related information like board s/n and other information into the new build EFI folder.
The script should also bring up errors or warnings if SMBIOS system type would no longer be supported and suggest a better system type.

**Comment by lzhoang2801** [comment]
1. I am focusing on creating the most complete EFI rather than adding fringe features that aren't the main reason users need this tool.
2. It is quite similar to the 'Update EFI' feature that will be implemented soon.
3. By default, the best SMBIOS will be selected based on the input configuration. Any changes for other reasons are the user’s responsibility. The tool will recheck and add the patch to skip the board ID check if necessary.
