### ISSUE TITLE
Samsung 970 Evo

### ISSUE THREAD

**Issue by hypermoist** [lzhoang2801/OpCore-Simplify#30]
It can work as long as you've updated your drives firmware, and you dont need NVMFix.kext

**Comment by lzhoang2801** [comment]
NVMeFix provides better power management capabilities, and it hasn't introduced any changes affecting compatibility. The Samsung 970 Evo can be installed due to Samsung's new firmware, but it still has a TRIM issue, requiring the value of SetApfsTrimTimeout to be set to 0 from macOS Monterey.

https://github.com/dortania/bugtracker/issues/192
