### ISSUE TITLE
It's not a issue but rather a question

### ISSUE THREAD

**Issue by st11felipe** [lzhoang2801/OpCore-Simplify#39]
I have installed an RTX 4070 Super and I want to buy an RX 570 8GB to install on my computer. Is it possible that your tool might recognize the RX 570 instead of the RTX 4070 Super?

**Comment by lzhoang2801** [comment]
It will automatically disable the RTX 4070 Super for you to ensure no issues when using macOS. You just need to connect the display cable to the RX 570

**Comment by CSATMRIT** [comment]
Hi I have an old real MacBook Pro  that have two graphic chip - nVidia and intel. Nvidia is broken but the OSX instalation doesn’t care instead of choose Intel. Is it possible to edit EFI in order the system select intel only?Thanks and please apologise for smugling this thread.Cesar Enviado do meu iPhoneEm 2 de nov. de 2024, à(s) 18:35, Hoang Hong Quan ***@***.***> escreveu:﻿
It will automatically disable the RTX 4070 Super for you to ensure no issues when using macOS. You just need to connect the display cable to the RX 570
